### ISSUE TITLE
Certain font-weights not registering

### ISSUE THREAD

**Issue by dubert** [domenic/svg2png#18]
When using `font-weight: 100` through `font-weight: 900` it seems as though only regular and bold are being used, and all other weights are being rounded up or down.

Each of these uses 100 through 900, and the svg preview shows the different weights, but when svg2png creates a png, it loses them.

![screen shot 2014-07-19 at 01 14 36](https://cloud.githubusercontent.com/assets/1843672/3633898/a06e7d62-0f03-11e4-8cee-9d06b43b310e.png)

**Comment by domenic** [comment]
Can you provide a small SVG test file so I can see if this is fixed in the latest PhantomJS?

**Comment by domenic** [comment]
Closing since no repro file was provided.
