### ISSUE TITLE
Potentially bad scaling at lower resolutions

### ISSUE THREAD

**Issue by TheunisKotze** [domenic/svg2png#21]
Not a bug in svg2png, possibly an issue with phantomjs or the svg's that I am generating, to help establish that I was wondering whether you may have come across bad scaling at low resolution?
You can see the thumbnail attached - it looks whitewashed and blurry.  When I scale the svg down to that size in chrome it looks much better.  
![gamingcape](https://cloud.githubusercontent.com/assets/436217/5427057/95b92428-838c-11e4-9ad1-10a7265dc668.png)

**Comment by domenic** [comment]
Can you provide a small SVG test file so I can see if this is fixed in the latest PhantomJS?

**Comment by domenic** [comment]
Closing since no file was provided.
