### ISSUE TITLE
Widths in percentages should be computed against the viewbox

### ISSUE THREAD

**Issue by domenic** [domenic/svg2png#22]
See #20 for background. For images like

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100%" height="100%" viewBox="-5 -5 10 10">
   <circle cx="0" cy="0" r="5"/>
</svg>
```

we should be inferring a width/height of 15 = 100% * (10 - (-5)). Currently the code assumes all widths are pixels, which is wrong.

**Comment by littlefyr** [comment]
@TheunisKotze is correct. Consider the results if you have `viewBox="400 400 20 20"` which is a completely permitted and reasonable value to have. In this case you'd have a square -380px in size, which is meaningless.  

Regardless, this is a terrible inference to make. The `viewBox` is not in pixels, they're in userSpace, which is unit-less. 

In this case if you rendered the SVG into a regular chrome window, and you made that window full screen, say 1200X1600px, the space would be 1600px X 1600px, the origin would be at 800,800 and your circle would have an 800px radius. If I built my SVG this way, then I want the image to be 1600 x 1600 or some such. 

The better solution for this type of issue is not to infer a size based on some calculation from the `viewBox` but to add the ability to specify the output dimensions (in px) and to have a default value (I'd suggest 1px x 1px to encourage people to use a meaningful value but you could infer it as you suggest here, I just think that's a bad idea) that is used when the height or width are in percentages.

**Comment by domenic** [comment]
Thanks for explaining. If someone wants to resurrect #32 by adding tests to it, that would solve the issue nicely, I think.

**Comment by littlefyr** [comment]
I'll take a look at this, but as I'm doing so, I'm seeing a few other errors in the code (not in the commit). For example, this chunk of code in converter.js gives the wrong result:
```javascript
        if (!width) {
            width = bbox.width + bbox.x;
        }
        if (!height) {
            height = bbox.height + bbox.y;
        }
```
the bounding box height and width is the height and width of all the things in that element (since its the `<svg>` element, that would be all the things), and the offset are relative to the origin of the user space. To see how that works, take your circle example and change the radius to 50. playing in chrome, the bbox.width and height are now 100 and the x and y values are both - 50.

**Comment by littlefyr** [comment]
I also noticed that some of your example images are going to give the wrong result on my test... a mac that doesn't have Segoe UI installed :)

It would be helpful if there were better instructions on how to run the tests locally,

**Comment by dottodot** [comment]
Is there any resolution to this. I have svgs with percentage width and height and I can only save them as a 100px x 100px png which is not ideal.

**Comment by dottodot** [comment]
@domenic that's awesome, works perfectly. Thanks for sorting
