### ISSUE TITLE
is it possible to write output to stream, not file

### ISSUE THREAD

**Issue by koutsenko** [domenic/svg2png#23]
Hello!
I'm writing a build script and want to avoid transient disk writes.
Because raw png isn't endpoint, I want optimize image using [pngquant](https://www.npmjs.com/package/pngquant).

**Comment by domenic** [comment]
I don't think so. PhantomJS's render() function seems to be one-shot, not streaming.

**Comment by koutsenko** [comment]
It's true, but there is a [possibility](http://phantomjs.org/api/webpage/method/render-base64.html) to write result to base64 string which can be decoded by nodejs natively...

**Comment by domenic** [comment]
Sure, but that's not streaming either, so all that will do is add overhead as encode to base64 then decode back to binary, and still end up with a big blob.
