### ISSUE TITLE
Not rendering transform attritubtes

### ISSUE THREAD

**Issue by Kurtz1993** [domenic/svg2png#24]
I tried to convert an SVG file with transform scale() and transform rotate(), but I can't get it to work. The conversion only outputs the images at their original coordinates but without any rotation or scale.

 ## Original SVG
![original svg](https://cloud.githubusercontent.com/assets/5412470/6900625/0ca5b7be-d6c5-11e4-9a29-c127d2de3d67.PNG)

## Converted jpg
![convertida](https://cloud.githubusercontent.com/assets/5412470/6900638/153ed1b2-d6c5-11e4-9f39-88350a213df3.PNG)

These are the properties that are not being converted:
style="transform: scale(1.9939797114561713) rotate(15.47907791300374925deg); transform-origin: 73.56616973876953px 56.75px;"

**Comment by domenic** [comment]
I mean, my guess would be PhantomJS does not support these :(.

I wonder if we should try PhantomJS 2.0 somehow...

**Comment by domenic** [comment]
Can you provide a small SVG test file so I can see if this is fixed in the latest PhantomJS?

**Comment by domenic** [comment]
Closing since no repro file was forthcoming.
