### ISSUE TITLE
readme missing basic info

### ISSUE THREAD

**Issue by posfan12** [domenic/svg2png#40]
The readme is missing basic information like:

What operating systems does this program run on?
How do you install the program?
How do you execute the program?
What is PhantomJS?

The docs say something about Node.js, but what is it?

**Comment by domenic** [comment]
This repo is meant for people already familiar with those technologies. You are welcome to add something to the wiki explaining them if you want.

**Comment by posfan12** [comment]
Okay, I just "explained" things to the best of my knowledge on the wiki. Thanks so much for your help!
