### ISSUE TITLE
External symbols not supported

### ISSUE THREAD

**Issue by Foul-Weather-Friend** [domenic/svg2png#43]
It seems that external symbols are not supported.

This works in all non IE browsers, should work here:
<use xlink:href="some-file.svg#some-symbol" />

**Comment by domenic** [comment]
I don't know what external symbols are, but presumably this is a PhantomJS limitation.

A test case would be helpful.

**Comment by jensfinnas** [comment]
Might "external symbols" mean non-ASCII characters? I'm struggling with that at least.

```
<svg xmlns="http://www.w3.org/2000/svg"><g><text x="50" y="50" font-size="15">åäö</text></g></svg>
```
Results in:

![foo](https://cloud.githubusercontent.com/assets/1089739/18888274/e17a03dc-84f7-11e6-94fc-aa864de4cc55.png)

**Comment by domenic** [comment]
That seems like a separate issue.

**Comment by jensfinnas** [comment]
https://github.com/domenic/svg2png/issues/63
