### ISSUE TITLE
How to create png from inline svg 

### ISSUE THREAD

**Issue by vbazurtob** [domenic/svg2png#46]
Hi,

Im trying to use this library but i'm not reading an svg file from the filesystem. I want to parse an svg string containing all the markup and then convert it to png and render it to the standard response with mime type png. How can I achieve this with this library?

I would start with the svg definition in a string variable like this:

var mySVG = "<svg>...</svg>"

svg2png(mySVG).then
...

or something like that

**Comment by ArunMichaelDsouza** [comment]
+1

**Comment by domenic** [comment]
This is probably a better question for StackOverflow. It should be pretty clear from the readme but someone else might be able to help you if you can't figure it out.
