### ISSUE TITLE
TypeError: `undefined` is not an object (evaluating el.viewBox.animVal)

### ISSUE THREAD

**Issue by eladnava** [domenic/svg2png#47]
Hi there,
Loving the package! Nice work. I use it on my [material-letter-icons](https://github.com/eladnava/material-letter-icons) package, and it's awesome!

Just one small hiccup -- when running `svg2png` on Windows, the following error is thrown:

![69862c4a-2591-11e6-8ea1-803a408f3aed](https://cloud.githubusercontent.com/assets/4394189/15804867/2df9cc56-2b20-11e6-9dd2-1ff12d488ade.png)

On Linux / Mac OS X, the error is not thrown and the `png` file is generated successfully.

The code used to run `svg2png`:
```js
    // Convert the SVG file into a PNG file using svg2png
    svg2png(outputSVGPath, outputPNGPath, {width: 512, height: 512}, function(err) {
        // Report error
        if (err) {
            return cb(err);
        }
        
        // Success!
        cb();
    });
```

The actual SVG being converted:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="532" height="532" viewBox="0 0 512 512">
    <circle cx="255" cy="255" r="230" fill="{c}" />
    <text x="255" y="246" alignment-baseline="central" text-anchor="middle" fill="#fff" font-size="275" font-weight="300" font-family="Roboto">A</text>
</svg>
```

The `svg2png` package version is `^2.1.0`.

Any help would be greatly appreciated!

**Comment by domenic** [comment]
I was not able to reproduce this on my Windows 10 computer :-/.
