### ISSUE TITLE
Not support textpath

### ISSUE THREAD

**Issue by yangpu** [domenic/svg2png#48]
Any plan to support SVG textPath?

**Comment by domenic** [comment]
That's up to the authors of PhantomJS.

**Comment by yangpu** [comment]
I have solved this issue which is not blocked by phantomjs, but Snap.Svg generates text-path on href reference without xlink namespace declaration, and it works after adding xmlns:xlink="http://www.w3.org/1999/xlink" to svg and replacing href by xlink:href before input SVG to svg2png.

Thanks for your help either.
