### ISSUE TITLE
Lots of whitespace added

### ISSUE THREAD

**Issue by callumacrae** [domenic/svg2png#49]
Hello!

I'm using svg2png through gulp-svg2png, and I'm having an issue: https://github.com/akoenig/gulp-svg2png/issues/22

Basically, after updating svg2png to 3, this happened:

![](https://cloud.githubusercontent.com/assets/472830/15857508/b53db666-2cb3-11e6-9369-ca2d9a0e3dac.png)

I'm guessing that it's a svg2png issue as I can't see anything in the gulp-svg2png code that could be causing this.

Any ideas?

**Comment by domenic** [comment]
Can you reproduce the issue using svg2png alone? I can't really help if I'm expected to debug someone else's package as well and don't even have a small repro case.

**Comment by callumacrae** [comment]
Here we go: https://github.com/callumacrae/svg2png-test

**Comment by domenic** [comment]
Awesome, thanks! It looks like you are doing everything right, and there is some kind of bug here that is preventing it from picking up the correct width/height... it isn't immediately obvious what, though. I'll try to give it a look.

**Comment by callumacrae** [comment]
Great, thank you!

I can't figure out the code myself, but if there's anything else I can do to help, let me know (or point me in the right direction).

**Comment by jasonalvis** [comment]
Hello,

Just seeing if there is an update for this issue?

Thank you
