### ISSUE TITLE
Local external images are not rendered

### ISSUE THREAD

**Issue by Clafou** [domenic/svg2png#53]
I can't seem to get image tags to work when they are local files. The SVG does display correctly when opened in a browser, but doesn't convert correctly. The linked image is missing from the output. See below for example:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="100px" height="100px" viewBox="0 0 100 100" xml:space="preserve">
<g>
<!--
This works:
    <image x="0" y="0" width="100%" height="100%" xlink:href="http://placekitten.com/100/100" />
This doesn't work: -->
    <image x="0" y="0" width="100%" height="100%" xlink:href="./kitten.png" />
</g>
</svg>
```

**Comment by domenic** [comment]
Really interesting bug, thanks! I guess to fix this we'll need to tell PhantomJS that the current document is located at a certain `file:` URL. I'm not sure what the API is for that, but it probably exists. Pull request welcome, or I can try to get working on it on my next free weekend.

**Comment by Clafou** [comment]
Thanks! I'm not sure it's about the path, as it also doesn't seem to work with a fully qualified path. Maybe PhantomJS is blocking file system resources?
For anyone looking for a workaround, it's still possible to embed bitmaps using base-64 encoding.
