### ISSUE TITLE
Not rendering images on server

### ISSUE THREAD

**Issue by dottodot** [domenic/svg2png#54]
I'm just testing my implementation on a new server and for some reason it's not rendering the images that are in the svg and I can't work out why. It works fine locally and the images are stored in cloudinary so should be accessible so not sure what I"m missing.

This is an example of an svg I'm trying to convert

https://s3.eu-central-1.amazonaws.com/boxxer/uploads/items/57c46a04f1dc422b002ff291.svg

but the result looks like

https://res.cloudinary.com/dot-to-dot-design/image/upload/f_auto,q_auto,w_600/boxxer_s3/uploads/items/57c46a04f1dc422b002ff291_1472543810612.png

My servers run flynn (bit like heroku)

Just can't think what would be causing it not to render correctly

**Comment by dottodot** [comment]
Also as extra information I currently have another implementation on a different server using v2 that works fine, as mentioned before running v3 locally also works. I'm really what to do to debug this, I'm not getting any error so really hard to know what's causing it not to render the images. For completeness here's my code

```
exports.createSvg = function(item_id, svg) {
    var timestamp = Date.now();
    var svg_path = 'uploads/items/' + item_id + '.svg';
    var png_path = 'uploads/items/' + item_id + '_' + timestamp + '.png';
    var svg_buffer = new Buffer(svg);
    var s3 = new AWS.S3();
    var params = {
        Bucket: sails.config.aws.bucket,
        Key: svg_path,
        ACL: 'public-read',
        Body: svg,
        ContentType: 'image/svg+xml'
    };
    var putObjectPromise = s3.putObject(params).promise();
    return putObjectPromise.then(function(data) {
        return svg2png(svg_buffer, {
            width: 600
        });
    }).then(function(data) {
        var params = {
            Bucket: sails.config.aws.bucket,
            Key: png_path,
            Body: data,
            ContentType: 'image/png'
        };
        var putObjectPromise = s3.putObject(params).promise();
        return putObjectPromise;
    }).then(function(resp) {
        return LineItem.update(item_id, {
            svg_path: svg_path,
            png_path: png_path
        });
    }).catch(function(err) {
        console.error(err);
        reject(err);
    });
};
```

**Comment by domenic** [comment]
Hmm. I was not able to reproduce this locally. If I sent that file through as a string directly (e.g. using `` Buffer.from(`...svg here...`) `` the result looks correct.

Could you create a reproduction case that I could run on my own computer, not involving S3 or servers or anything?

**Comment by dottodot** [comment]
Unfortunately the problem only occurs on the version uploaded to the server, and only thing I can think of is that the images stored in cloundinary and referenced in the defs are not loading, but this shouldn't be the case as there are no restrictions on being able to access those images.

**Comment by domenic** [comment]
Maybe your server has a firewall preventing outbound connections or similar.

Going to close since this isn't really actionable for me since I have no way of reproducing and debugging it :(.
