### ISSUE TITLE
example does not seem to work

### ISSUE THREAD

**Issue by chovy** [domenic/svg2png#57]
```
  return new Promise((resolve, reject) => {
    const fs = require("pn/fs"); // https://www.npmjs.com/package/pn
    const svg2png = require("svg2png");
    fs.writeFileSync('./chart.svg', chart);

    fs.readFile("./chart.svg")
      .then(svg2png)
      .then(buffer => {
        fs.writeFile("./chart.png", buffer);
      })
      .then(() => {
        resolve(streams);
      })
      .catch(reject);
  });
```

I never get to the `buffer` callback. The `chart.svg` has svg in it:

`<svg width="300" height="300" class="shadow"><g transform="translate(150,150)"><path d="M8.572527594031473e-15,-140A140,140 0 1,1 -43.26237921249269,133.14791228132148L0,0Z" fill="#e75244" style="fill-opacity: 0.15; stroke: #e75244; stroke-width: 2px;"></path><path d="M-43.26237921249269,133.14791228132148A140,140 0 0,1 9.862739597592311e-14,-140L0,0Z" fill="#33bb9d" style="fill-opacity: 0.15; stroke: #33bb9d; stroke-width: 2px;"></path><text transform="translate(69.13818384165964,10.950412552816177)" text-anchor="middle" style="fill: #e75244; font-size: 18px;">Male (55%)</text><text transform="translate(-69.13818384165964,-10.950412552816214)" text-anchor="middle" style="fill: #33bb9d; font-size: 18px;">Female (45%)</text></g></svg>
`

I get an error when I look at the reject:

```[Error: Unknown encoding: <svg width="300" height="300" class="shadow"><g transform="translate(150,150)"><path d="M8.572527594031473e-15,-140A140,140 0 1,1 -43.26237921249269,133.14791228132148L0,0Z" fill="#e75244" style="fill-opacity: 0.15; stroke: #e75244; stroke-width: 2px;"></path><path d="M-43.26237921249269,133.14791228132148A140,140 0 0,1 9.862739597592311e-14,-140L0,0Z" fill="#33bb9d" style="fill-opacity: 0.15; stroke: #33bb9d; stroke-width: 2px;"></path><text transform="translate(69.13818384165964,10.950412552816177)" text-anchor="middle" style="fill: #e75244; font-size: 18px;">Male (55%)</text><text transform="translate(-69.13818384165964,-10.950412552816214)" text-anchor="middle" style="fill: #33bb9d; font-size: 18px;">Female (45%)</text></g></svg>]```

I'm guessing `d3-node` doesn't create the xml doc properly.

well fixing that still didn't solve my problem. I think you have a bug with the options you pass to phantom. It is expecting options to be defined.

I passed in an empty object: `svg2png(string, {})` and it got through `const cp = childProcess.execFile(phantomjsCmd, getPhantomJSArgs(options), { maxBuffer: Infinity });` line #13. But then it just hangs.

I tried using `svgexport` cli tool `npm i -g svgexport` and it uses phantomjs and works fine.

This entire function assumes `options` is defined:

```
function getPhantomJSArgs(options) {
    if (options.filename !== undefined && options.url !== undefined) {
        throw new Error("Cannot specify both filename and url options");
    }

    // Convert filename option to url option
    if (options.filename !== undefined) {
        options = Object.assign({ url: fileURL(options.filename) }, options);
        delete options.filename;
    }

    return [
        converterFileName,
        options === undefined ? "undefined" : JSON.stringify(options)
    ];
}
```

You need to do `if (options && options.filename){} ` etc

**Comment by domenic** [comment]
Thanks, fixed. Tip: [don't use the Promise constructor like that.](http://stackoverflow.com/q/23803743/3191)

**Comment by chovy** [comment]
why not?

**Comment by domenic** [comment]
Did you click the link?

**Comment by chovy** [comment]
Yeah. I did not see anything specifically as to why you should not use `return new Promise()`

**Comment by domenic** [comment]
No. The link is very clear about this, so if that does not help, then I guess I cannot help by re-explaining it. So nevermind.

**Comment by chovy** [comment]
heh. ok.
