### ISSUE TITLE
changed requirements

### ISSUE THREAD

**Issue by riw** [domenic/svg2png#58]
svg2png no longer works on node v5 because of the default function parameters
please remove those or update the readme

**Comment by pjeweb** [comment]
I would greatly appreciate support for v4. We cannot update all of our machines to v5/v6.

**Comment by satazor** [comment]
Same here!

**Comment by domenic** [comment]
The readme already stated the requirements and has for the duration of 2.x.

**Comment by riw** [comment]
sorry if i'm wrong (english is not my native language) but the readme says everything below node version 5.0 isn't supported - i thought that means that this plugin supports >= v5

**Comment by domenic** [comment]
Ah, yeah, sorry about that. I will release v3.0.0 some time then. Should I unpublish 2.1.1? People got mad last time I did that.

**Comment by aredridel** [comment]
Not unpublish, but publish a newer version with the fix, like any regression.

**Comment by domenic** [comment]
This wasn't a regression. The mistake was in bumping the version number only patch instead of major, so I intend to address that. The question is what to do about the version with the wrong number.

**Comment by aredridel** [comment]
That'd be a regression in v2 if you ask me, it used to work, now it doesn't.

**Comment by domenic** [comment]
OK, well I disagree.

**Comment by simon360** [comment]
I agree that this is a regression. It's also an easy one to fix - see #60. Could there be a 3.1.2 release with that fix, and an understanding that future versions may be breaking? I'd rather not have to pin my dependencies to 3.1.0 just because our build server isn't bleeding edge.

**Comment by owen-hong** [comment]
Same here!

**Comment by domenic** [comment]
It sounds like I should unpublish 2.1.1 since it is causing people such trouble. And probably 2.1.0 since it is buggy (thus the 2.1.0 release). I have no intention of moving back language versions.

**Comment by domenic** [comment]
OK. npm will not let me unpublish versions older than 24 hours, so this is as fixed as it is going to get. People will just have to pin their versions if they are using 3.x. I am sorry about that; it was a clear mistake. But I am not willing to maintain or support two release lines going forward, so I will not be publishing any 3.1.2. That is final.
