### ISSUE TITLE
3.1.1 introduced a breaking change

### ISSUE THREAD

**Issue by jefflembeck** [domenic/svg2png#59]
https://github.com/domenic/svg2png/commit/c266004443015777c6827138050dad0ac7e54cb2#diff-e6cb7d06781cf12f8e2d82b6ebdf7061R28

This moves the requirement for Node 4 to Node 6

**Comment by jefflembeck** [comment]
Nevermind, this is a dupe of https://github.com/domenic/svg2png/issues/58, closing.

**Comment by jantimon** [comment]
Could you please provide a es5 version?
I am used this library in a node 0.12.x plugin - don't see why this plugin should limit its users to node 6

**Comment by domenic** [comment]
I am not interested in supporting old versions of Node. You are welcome to create your own fork, or use a transpiler, if you want to do that.
