### ISSUE TITLE
svg2png v4.0.0 node v5.7.1 require error

### ISSUE THREAD

**Issue by owen-hong** [domenic/svg2png#61]
```javascript
const svg2png = require("svg2png");
```

Node :v5.7.1 
svg2png: v4.0.0

![image](https://cloud.githubusercontent.com/assets/6466628/18502143/e53f2260-7a87-11e6-8754-d51c5def3bb8.png)

**Comment by Muini** [comment]
Same error here.

**Comment by domenic** [comment]
The readme and release notes are very clear that Nodd v6 is required.
