### ISSUE TITLE
v3.1.1 breaking change

### ISSUE THREAD

**Issue by mifi** [domenic/svg2png#70]
3.1.1 requires node >=5, whereas 3.1.0 does not. 3.1.1 breaks every project that depends on yours because of the way semver works. I see that you published a 4.0.0, but you should also publish a 3.1.2 which reverts the breaking change.

**Comment by domenic** [comment]
Sorry, I'm not interested in maintaining the 3.x release line further.

**Comment by mifi** [comment]
Are you not interested in inviting someone to help you maintain it either? It's not very nice to just break the most used version branch and then just leave it and refuse to fix it when there are lots of people using tools that depend on it.
