### ISSUE TITLE
I add some new function,I can get the svg by the upper left corner coordinates

### ISSUE THREAD

**Issue by huhu502** [domenic/svg2png#75]
1. converter.js
    setSVGDimensions(page, dimensions.width, dimensions.height);

            page.viewportSize = {
                width: dimensions.width,
                height: dimensions.height
            };
            page.clipRect = {
                top: options.top,
                left: options.left,
                width: dimensions.width- 2*options.left,
                height: dimensions.height-2*options.top
            };
2,the use of the funciton
  const fs = require("pn/fs");
            const svg2png = require("svg2png");
            fs.readFile(svgName+".svg")
                .then(input=>svg2png(input, {top:top,left:left, width: 2*left+100, height: 2*top+100 }))
               .then(buffer => fs.writeFile(pngName+".png", buffer))
             .catch(e => console.error(e));

**Comment by domenic** [comment]
I can't tell what the issue is here.
