### ISSUE TITLE
Module not found: 'child_process' 

### ISSUE THREAD

**Issue by PeteMichaud** [domenic/svg2png#86]
I'm trying to use this package, but I get this error when I try to require it. The issue seems to be that the `pn` package relies on `child_process` which apparently doesn't exist anymore: https://www.npmjs.com/package/child_process

This package probably needs to be updated to use a newer or existing package, but I don't know enough about how or why it was used to make the change myself.

**Comment by domenic** [comment]
child_process is built in to Node.js: https://nodejs.org/docs/latest/api/child_process.html

**Comment by PeteMichaud** [comment]
I see, so I can only use this package server side, not, for example, in a react app?

My use case is that my react app generates an svg dynamically, and I wanted to enable downloading from that app, but it seems like I'll have to pass the raw svg document back to the server for processing before the download.

**Comment by domenic** [comment]
Correct.
