### ISSUE TITLE
Question : Can I pass SVG as markup

### ISSUE THREAD

**Issue by gs-akhan** [domenic/svg2png#89]
HI,
I was looking for anyway I can pass data as markup instead of SVG file. 

Thanks

**Comment by domenic** [comment]
Yes; svg2png accepts a Buffer parameter. If you need help figuring out how to create a buffer with a given string, I'd suggest consulting the Node.js docs, or StackOverflow.

**Comment by gs-akhan** [comment]
Got it. Thank you very much..
