### ISSUE TITLE
Electron build. Error on Windows.

### ISSUE THREAD

**Issue by ms4ever7** [domenic/svg2png#92]
I am using Atom Electron to build my project and when i am trying to use [this](https://www.npmjs.com/package/svg2png) module i have an error

`Uncaught (in promise) Error: write EPIPE(…)exports._errnoException @ util.js:890Socket._writeGeneric @ net.js:681Socket._write @ net.js:700doWrite @ _stream_writable.js:301clearBuffer @ _stream_writable.js:404Writable.uncork @ _stream_writable.js:238Writable.end @ _stream_writable.js:448Socket.end @ net.js:408writeBufferInChunks @ E:\dye\dyegraph-win32-ia32\resources\app\node_modules\svg2png\lib\svg2png.js:54Promise.resolve.then @ E:\dye\dyegraph-win32-ia32\resources\app\node_modules\svg2png\lib\svg2png.js:15
util.js:890 Uncaught (in promise) Error: spawn E:\dye\dyegraph-win32-ia32\resources\app\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs ENOENT(…)exports._errnoException @ util.js:890ChildProcess._handle.onexit @ internal/child_process.js:182onErrorNT @ internal/child_process.js:348_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98`

The problem is that on MacOS everything is Ok , but on Windows i get this error

**Comment by domenic** [comment]
I don't have any experience with Atom Electron, so am unlikely to be able to help. You may wish to ask for support in a forum dedicated to that technology.

**Comment by ms4ever7** [comment]
@domenic  look at [this](https://github.com/filamentgroup/svg-to-png/issues/28) please, 
after that issue i was trying to find another package, but there also was problem on windows
Maybe u'll know something about that problem
would be very grateful for your help

**Comment by tzarebczan** [comment]
Did you ever find the solution to this?
