### ISSUE TITLE
weird phantomjs/svg2png error

### ISSUE THREAD

**Issue by operolim** [domenic/svg2png#94]
I keep getting the error below, whether I pass the svg2png constructor the width and height of svg or not. I've looked everywhere for a solution or a workaround, but I haven't found one yet and I was hoping someone could shed some light on how to resolve this. 

`svg2png(Buffer.from(svgText, 'utf8'), {width: 300, height: 400})`

`Error: Command failed: /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /app/node_modules/svg2png/lib/converter.js {"width": 300, "height": 400}`

**Comment by domenic** [comment]
Can you try it on a very simple SVG, and if that still fails, post the whole code snippet?

**Comment by operolim** [comment]
Actually I'm only seeing this error in my dev environment. It works fine locally.

**Comment by operolim** [comment]
Any updates on this?

**Comment by domenic** [comment]
Given that you have given no way to reproduce the issue, no. Closing. Sounds like an issue with your environment, not svg2png.
